  mergepdf:
    <<: *common
    image: islandora/mergepdf:${ISLANDORA_TAG}
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY
