version: 2
release:
  disable: "{{ .Env.GORELEASER_DISABLE_SCM_RELEASE }}"
before:
  hooks:
    - ./scripts/check-sitectl-core-version.sh v0.40.0
    - go mod tidy
builds:
  - binary: sitectl-isle
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^.github"
brews:
  - name: sitectl-isle
    description: "A sitectl plugin for Islandora stacks"
    homepage: "https://github.com/libops/sitectl-isle"
    license: MIT
    commit_author:
      name: sitectl-dev[bot]
      email: 2408410+sitectl-dev[bot]@users.noreply.github.com
    repository:
      owner: libops
      name: homebrew
      branch: "{{ .ProjectName }}-{{ .Version }}"
      token: "{{ .Env.HOMEBREW_REPO_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: libops
          name: homebrew
          branch: main
    dependencies:
      - name: "libops/homebrew/sitectl"
      - name: "libops/homebrew/sitectl-drupal"
nfpms:
  - id: sitectl-isle
    package_name: sitectl-isle
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: libops
    homepage: "https://github.com/libops/sitectl-isle"
    description: "A sitectl plugin for Islandora (ISLE) sites"
    maintainer: "Joe Corall <joe@libops.io>"
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
    mtime: "{{ .CommitDate }}"
    ids:
      - sitectl-isle
    dependencies:
      - sitectl
      - sitectl-drupal
    overrides:
      deb:
        dependencies:
          - sitectl (>= 0.40.0)
          - sitectl-drupal (>= 0.10.0)
      rpm:
        dependencies:
          - sitectl >= 0.40.0
          - sitectl-drupal >= 0.10.0
      apk:
        dependencies:
          - sitectl>=0.40.0
          - sitectl-drupal>=0.10.0
