http:
  services:
    triplet:
      loadBalancer:
        servers:
          - url: {{UPSTREAM_URL}}
  routers:
    triplet:
      rule: Host(`localhost`) && PathPrefix(`/iiif`)
      service: triplet
