name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    uses: libops/.github/.github/workflows/sitectl-plugin-goreleaser.yaml@96f2b94e80160824e43e526f73bc73673c39b152 # main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      go-version: ">=1.26.1"
      package-name: sitectl-isle
