name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    uses: libops/terraform-linux-packages/.github/workflows/reusable-goreleaser.yaml@main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      go-version: ">=1.25.3"
      publish-package-repo: true
      package-name: sitectl-isle
      package-repo-prefix: sitectl
      package-repo-label: sitectl
      package-public-key-name: sitectl-archive-keyring
      gcp-project: ${{ vars.LIBOPS_PACKAGES_GCLOUD_PROJECT }}
      workload-identity-provider: ${{ vars.LIBOPS_PACKAGES_GCLOUD_OIDC_POOL }}
      service-account: ${{ vars.LIBOPS_PACKAGES_GSA }}
      gcs-bucket: ${{ vars.LIBOPS_PACKAGES_GCS_BUCKET }}
      aptly-gpg-key-id: ${{ vars.LIBOPS_PACKAGES_APTLY_GPG_KEY_ID }}
      aptly-gpg-private-key-secret: ${{ vars.LIBOPS_PACKAGES_APTLY_GPG_PRIVATE_KEY_SECRET }}
      aptly-gpg-passphrase-secret: ${{ vars.LIBOPS_PACKAGES_APTLY_GPG_PASSPHRASE_SECRET }}
