name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    uses: libops/.github/.github/workflows/sitectl-plugin-goreleaser.yaml@2b484149fca1653d2bd48311929efca21f32214d # main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      go-version: "1.26.x"
      package-name: sitectl-isle
