name: integration-test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: integration-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-isle:
    name: sitectl create isle fcrepo=${{ matrix.fcrepo_state }} blazegraph=${{ matrix.blazegraph_state }} bot-mitigation=${{ matrix.bot_mitigation_state }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - fcrepo_state: on
            blazegraph_state: on
            isle_file_system_uri: public
            iiif_implementation: triplet
            iiif_topology: disabled
            bot_mitigation_state: off
          - fcrepo_state: off
            blazegraph_state: on
            isle_file_system_uri: public
            iiif_implementation: triplet
            iiif_topology: disabled
            bot_mitigation_state: off
          - fcrepo_state: off
            blazegraph_state: off
            isle_file_system_uri: private
            iiif_implementation: triplet
            iiif_topology: disabled
            bot_mitigation_state: on
    uses: libops/.github/.github/workflows/sitectl-create-smoke-test.yaml@da242aa070fa29b4028c5e03884b69857ea13fdf # main
    with:
      plugin: isle
      create-definition: default
      template-repo: https://github.com/libops/isle
      create-args: >-
        --fcrepo ${{ matrix.fcrepo_state }}
        --blazegraph ${{ matrix.blazegraph_state }}
        --isle-file-system-uri ${{ matrix.isle_file_system_uri }}
        --iiif ${{ matrix.iiif_implementation }}
        --iiif-topology ${{ matrix.iiif_topology }}
        --bot-mitigation ${{ matrix.bot_mitigation_state }}
      run-verify: true
      verify-args: >-
        --fcrepo ${{ matrix.fcrepo_state }}
        --blazegraph ${{ matrix.blazegraph_state }}
        --isle-file-system-uri ${{ matrix.isle_file_system_uri }}
        --iiif ${{ matrix.iiif_implementation }}
        --iiif-topology ${{ matrix.iiif_topology }}
        --bot-mitigation ${{ matrix.bot_mitigation_state }}
        --demo-objects
      checkout-path: sitectl-isle
      checkout-source: template
      project-path: isle-site-template
      local-plugin-path: sitectl-isle
      sitectl-repository: libops/sitectl
      sitectl-ref: 72c60889d65fd5d7e5d6a2e644a30b53d1699bcd # v0.38.0
      packages: sitectl-drupal
      timeout-minutes: 120
